[package]
name = "atelier-hosted"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[dependencies]
futures.workspace = true
object_store.workspace = true
rustyriver.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
tokio.workspace = true

[dev-dependencies]
atelier-sdk = { path = "../core" }
rusqlite.workspace = true
tempfile.workspace = true

[lints]
workspace = true
